import { Download } from "lucide-react";
import { requireSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { PageHeader } from "@/components/ops/page-header";
import { MetricCard } from "@/components/ops/metric-card";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const REPORTS = [
  {
    type: "settlement",
    title: "Settlement ledger export",
    description: "Full settlement ledger with lifecycle timestamps, amounts and fees across both corridors.",
  },
  {
    type: "reconciliation",
    title: "Reconciliation export",
    description: "External references, match confidence, status and exceptions for finance review.",
  },
  {
    type: "audit",
    title: "Audit evidence package",
    description: "Immutable audit trail of every operator and system action for compliance and regulators.",
  },
] as const;

export default async function ReportsPage() {
  const { organization, user } = await requireSession();

  const [settlementCount, reconciliationCount, auditCount] = await Promise.all([
    prisma.settlement.count({ where: { organizationId: organization.id } }),
    prisma.reconciliationRecord.count({ where: { organizationId: organization.id } }),
    prisma.auditLog.count({ where: { organizationId: organization.id } }),
  ]);

  const counts: Record<string, number> = {
    settlement: settlementCount,
    reconciliation: reconciliationCount,
    audit: auditCount,
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Generate enterprise settlement, reconciliation and audit exports for finance and compliance."
      />

      <div className="grid gap-3 sm:grid-cols-3">
        <MetricCard label="Settlement records" value={settlementCount} hint="Exportable rows" />
        <MetricCard label="Reconciliation records" value={reconciliationCount} hint="Exportable rows" />
        <MetricCard label="Audit events" value={auditCount} hint="Exportable rows" />
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        {REPORTS.map((report) => (
          <Card key={report.type} className="flex flex-col">
            <CardHeader>
              <CardTitle>{report.title}</CardTitle>
              <CardDescription>{report.description}</CardDescription>
            </CardHeader>
            <CardContent className="mt-auto space-y-3">
              <dl className="grid grid-cols-2 gap-y-2 border-t border-slate-100 pt-3 text-xs">
                <dt className="text-slate-400">Records ready</dt>
                <dd className="text-right font-medium tabular-nums text-slate-700">{counts[report.type]}</dd>
                <dt className="text-slate-400">Generated</dt>
                <dd className="text-right text-slate-600">On demand</dd>
                <dt className="text-slate-400">Generated by</dt>
                <dd className="truncate text-right text-slate-600">{user.name}</dd>
                <dt className="text-slate-400">Formats</dt>
                <dd className="text-right text-slate-600">CSV · JSON</dd>
              </dl>
              <div className="flex gap-2">
                <a
                  href={`/api/reports?type=${report.type}&format=csv`}
                  className={cn(buttonVariants({ variant: "primary", size: "sm" }), "flex-1")}
                >
                  <Download className="h-3.5 w-3.5" />
                  CSV
                </a>
                <a
                  href={`/api/reports?type=${report.type}&format=json`}
                  className={cn(buttonVariants({ variant: "outline", size: "sm" }), "flex-1")}
                >
                  <Download className="h-3.5 w-3.5" />
                  JSON
                </a>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <p className="text-xs text-slate-500">
        Exports respect your organization scope and are generated on demand from live data.
      </p>
    </div>
  );
}
